apiVersion: v1
kind: Namespace
metadata:
  name: deployment-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: deployment-ns
spec:
  selector:
    matchLabels:
      name: nginx-app
  template:
    metadata:
      labels:
        name: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: deployment-ns
spec:
  type: NodePort
  selector:
    name: nginx-app
  ports:
    - port: 80
