apiVersion: v1
kind: Namespace
metadata:
  name: pod-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: pod-ns
spec:
  containers:
    - image: nginx
      name: nginx-pod
      ports:
        - containerPort: 80
          name: http